-- ============================================================
-- Migration 001: Add requested_spec_* and returned_spec_* columns
-- to est_bnz_ross and est_bnz_dazpak
-- Target: dev-estimates branch ONLY
-- ============================================================

-- --- est_bnz_ross ------------------------------------------------
ALTER TABLE est_bnz_ross
    ADD COLUMN IF NOT EXISTS requested_spec_bag              TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_size             TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_substrate        TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_finish           TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_material         TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_embellishment    TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_fill_style       TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_seal_type        TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_gusset_style     TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_gusset_details   TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_zipper           TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_tear_notch       TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_hole_punch       TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_corners          TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_printing_method  TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_quantities       TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_bag               TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_size              TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_substrate         TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_finish            TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_material          TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_embellishment     TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_fill_style        TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_seal_type         TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_gusset_style      TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_gusset_details    TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_zipper            TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_tear_notch        TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_hole_punch        TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_corners           TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_printing_method   TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_quantities        TEXT;

-- --- est_bnz_dazpak ----------------------------------------------
ALTER TABLE est_bnz_dazpak
    ADD COLUMN IF NOT EXISTS requested_spec_bag              TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_size             TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_substrate        TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_finish           TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_material         TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_embellishment    TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_fill_style       TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_seal_type        TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_gusset_style     TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_gusset_details   TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_zipper           TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_tear_notch       TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_hole_punch       TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_corners          TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_printing_method  TEXT,
    ADD COLUMN IF NOT EXISTS requested_spec_quantities       TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_bag               TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_size              TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_substrate         TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_finish            TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_material          TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_embellishment     TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_fill_style        TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_seal_type         TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_gusset_style      TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_gusset_details    TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_zipper            TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_tear_notch        TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_hole_punch        TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_corners           TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_printing_method   TEXT,
    ADD COLUMN IF NOT EXISTS returned_spec_quantities        TEXT;
